export const INDEXES = [
  { symbol: '^NSEI', name: 'NIFTY 50' },
  { symbol: '^BSESN', name: 'SENSEX' },
  { symbol: '^NSEBANK', name: 'NIFTY BANK' },
  { symbol: '^CNXIT', name: 'NIFTY IT' },
  { symbol: '^CNXAUTO', name: 'NIFTY AUTO' },
  { symbol: '^CNXPHARMA', name: 'NIFTY PHARMA' },
  { symbol: '^CNXENERGY', name: 'NIFTY ENERGY' },
  { symbol: '^CNXFMCG', name: 'NIFTY FMCG' },
  { symbol: '^CNXINFRA', name: 'NIFTY INFRA' },
  { symbol: '^CNXREALTY', name: 'NIFTY REALTY' },
];

export const NIFTY_50 = [
  { symbol: 'RELIANCE.NS', name: 'Reliance Industries' },
  { symbol: 'TCS.NS', name: 'Tata Consultancy Services' },
  { symbol: 'HDFCBANK.NS', name: 'HDFC Bank' },
  { symbol: 'ICICIBANK.NS', name: 'ICICI Bank' },
  { symbol: 'INFY.NS', name: 'Infosys' },
  { symbol: 'HINDUNILVR.NS', name: 'Hindustan Unilever' },
  { symbol: 'ITC.NS', name: 'ITC Limited' },
  { symbol: 'SBIN.NS', name: 'State Bank of India' },
  { symbol: 'BHARTIARTL.NS', name: 'Bharti Airtel' },
  { symbol: 'KOTAKBANK.NS', name: 'Kotak Mahindra Bank' },
  { symbol: 'LT.NS', name: 'Larsen & Toubro' },
  { symbol: 'AXISBANK.NS', name: 'Axis Bank' },
  { symbol: 'ASIANPAINT.NS', name: 'Asian Paints' },
  { symbol: 'MARUTI.NS', name: 'Maruti Suzuki' },
  { symbol: 'SUNPHARMA.NS', name: 'Sun Pharmaceutical' },
  { symbol: 'TITAN.NS', name: 'Titan Company' },
  { symbol: 'BAJFINANCE.NS', name: 'Bajaj Finance' },
  { symbol: 'ULTRACEMCO.NS', name: 'UltraTech Cement' },
  { symbol: 'WIPRO.NS', name: 'Wipro' },
  { symbol: 'HCLTECH.NS', name: 'HCL Technologies' },
  { symbol: 'NTPC.NS', name: 'NTPC Limited' },
  { symbol: 'M&M.NS', name: 'Mahindra & Mahindra' },
  { symbol: 'ADANIENT.NS', name: 'Adani Enterprises' },
  { symbol: 'ONGC.NS', name: 'Oil & Natural Gas Corporation' },
  { symbol: 'POWERGRID.NS', name: 'Power Grid Corporation' },
  { symbol: 'JSWSTEEL.NS', name: 'JSW Steel' },
  { symbol: 'TATASTEEL.NS', name: 'Tata Steel' },
  { symbol: 'ADANIPORTS.NS', name: 'Adani Ports & SEZ' },
  { symbol: 'COALINDIA.NS', name: 'Coal India' },
  { symbol: 'HINDALCO.NS', name: 'Hindalco Industries' },
  { symbol: 'GRASIM.NS', name: 'Grasim Industries' },
  { symbol: 'BAJAJFINSV.NS', name: 'Bajaj Finserv' },
  { symbol: 'NESTLEIND.NS', name: 'Nestle India' },
  { symbol: 'TECHM.NS', name: 'Tech Mahindra' },
  { symbol: 'INDUSINDBK.NS', name: 'IndusInd Bank' },
  { symbol: 'EICHERMOT.NS', name: 'Eicher Motors' },
  { symbol: 'CIPLA.NS', name: 'Cipla' },
  { symbol: 'TATAMOTORS.NS', name: 'Tata Motors' },
  { symbol: 'SBILIFE.NS', name: 'SBI Life Insurance' },
  { symbol: 'DRREDDY.NS', name: "Dr. Reddy's Laboratories" },
  { symbol: 'HDFCLIFE.NS', name: 'HDFC Life Insurance' },
  { symbol: 'BPCL.NS', name: 'Bharat Petroleum' },
  { symbol: 'APOLLOHOSP.NS', name: 'Apollo Hospitals' },
  { symbol: 'BRITANNIA.NS', name: 'Britannia Industries' },
  { symbol: 'DIVISLAB.NS', name: "Divi's Laboratories" },
  { symbol: 'HEROMOTOCO.NS', name: 'Hero MotoCorp' },
  { symbol: 'BAJAJ-AUTO.NS', name: 'Bajaj Auto' },
  { symbol: 'UPL.NS', name: 'UPL Limited' },
  { symbol: 'LTIM.NS', name: 'LTIMindtree' },
];

export const SECTORS = {
  IT: [
    { symbol: 'TCS.NS', name: 'TCS' },
    { symbol: 'INFY.NS', name: 'Infosys' },
    { symbol: 'HCLTECH.NS', name: 'HCL Tech' },
    { symbol: 'WIPRO.NS', name: 'Wipro' },
    { symbol: 'TECHM.NS', name: 'Tech Mahindra' },
    { symbol: 'LTIM.NS', name: 'LTIMindtree' },
    { symbol: 'PERSISTENT.NS', name: 'Persistent Systems' },
    { symbol: 'COFORGE.NS', name: 'Coforge' },
  ],
  BANKING: [
    { symbol: 'HDFCBANK.NS', name: 'HDFC Bank' },
    { symbol: 'ICICIBANK.NS', name: 'ICICI Bank' },
    { symbol: 'SBIN.NS', name: 'SBI' },
    { symbol: 'AXISBANK.NS', name: 'Axis Bank' },
    { symbol: 'KOTAKBANK.NS', name: 'Kotak Bank' },
    { symbol: 'INDUSINDBK.NS', name: 'IndusInd Bank' },
    { symbol: 'BANKBARODA.NS', name: 'Bank of Baroda' },
    { symbol: 'PNB.NS', name: 'PNB' },
  ],
  AUTO: [
    { symbol: 'TATAMOTORS.NS', name: 'Tata Motors' },
    { symbol: 'M&M.NS', name: 'M&M' },
    { symbol: 'MARUTI.NS', name: 'Maruti Suzuki' },
    { symbol: 'EICHERMOT.NS', name: 'Eicher Motors' },
    { symbol: 'HEROMOTOCO.NS', name: 'Hero MotoCorp' },
    { symbol: 'BAJAJ-AUTO.NS', name: 'Bajaj Auto' },
    { symbol: 'TVSMOTOR.NS', name: 'TVS Motor' },
  ],
  ENERGY: [
    { symbol: 'RELIANCE.NS', name: 'Reliance' },
    { symbol: 'ONGC.NS', name: 'ONGC' },
    { symbol: 'NTPC.NS', name: 'NTPC' },
    { symbol: 'POWERGRID.NS', name: 'Power Grid' },
    { symbol: 'BPCL.NS', name: 'BPCL' },
    { symbol: 'IOC.NS', name: 'IOC' },
    { symbol: 'GAIL.NS', name: 'GAIL' },
    { symbol: 'ADANIGREEN.NS', name: 'Adani Green' },
  ],
  PHARMA: [
    { symbol: 'SUNPHARMA.NS', name: 'Sun Pharma' },
    { symbol: 'CIPLA.NS', name: 'Cipla' },
    { symbol: 'DRREDDY.NS', name: 'Dr Reddys' },
    { symbol: 'DIVISLAB.NS', name: 'Divis Lab' },
    { symbol: 'APOLLOHOSP.NS', name: 'Apollo Hospital' },
    { symbol: 'AUROPHARMA.NS', name: 'Aurobindo Pharma' },
    { symbol: 'LUPIN.NS', name: 'Lupin' },
  ]
};
